# -*- coding: utf-8 -*-
"""Task 1(Extract).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Enjpf9ZufZydEBNMhvJ8fPRCJz__edL4
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

data = pd.read_csv('https://raw.githubusercontent.com/codewithharsha/ETL-Pipeline/refs/heads/main/air_pollution_china.csv')

data.to_csv('air_pollution_china.csv')

